tierra_topicsolved_controller_mark:
    path: /topicsolved/mark/{solve}/{post_id}
    defaults: { _controller: tierra.topicsolved.controller:mark }
    requirements:
        solve: solved|unsolved
        post_id: \d+
